{
	"version": 1663708931,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"c2webappstart.js",
		"Cosmic Jump/Assets/background/sprite2-sheet0.png",
		"Cosmic Jump/Assets/background/tiledbackground.png",
		"Cosmic Jump/Assets/background/background-sheet0.png",
		"Cosmic Jump/Assets/background/playbutton-sheet0.png",
		"Cosmic Jump/Assets/background/instructionbutton-sheet0.png",
		"Cosmic Jump/Assets/background/quitbutton-sheet0.png",
		"Cosmic Jump/Assets/background/gamename-sheet0.png",
		"Cosmic Jump/Assets/background/level1button-sheet0.png",
		"Cosmic Jump/Assets/background/level2button-sheet0.png",
		"Cosmic Jump/Assets/background/level3button-sheet0.png",
		"Cosmic Jump/Assets/background/backbutton-sheet0.png",
		"Cosmic Jump/Assets/background/sprite6-sheet0.png",
		"Cosmic Jump/Assets/background/instructiontext-sheet0.png",
		"Cosmic Jump/Assets/background/bg-sheet0.png",
		"Cosmic Jump/Assets/background/player-sheet0.png",
		"Cosmic Jump/Assets/background/player-sheet1.png",
		"Cosmic Jump/Assets/background/mutebutton-sheet0.png",
		"Cosmic Jump/Assets/background/ground-sheet0.png",
		"Cosmic Jump/Assets/background/spikes-sheet0.png",
		"Cosmic Jump/Assets/background/enemy-sheet0.png",
		"Cosmic Jump/Assets/background/enemy-sheet1.png",
		"Cosmic Jump/Assets/background/wall-sheet0.png",
		"Cosmic Jump/Assets/background/sprite-sheet0.png",
		"Cosmic Jump/Assets/background/gotol2-sheet0.png",
		"Cosmic Jump/Assets/background/gotol1-sheet0.png",
		"Cosmic Jump/Assets/background/gotomm-sheet0.png",
		"Cosmic Jump/Assets/background/gotol3-sheet0.png",
		"Cosmic Jump/Assets/background/sprite7-sheet0.png",
		"Cosmic Jump/Assets/background/sprite8-sheet0.png",
		"Cosmic Jump/Assets/background/sprite9-sheet0.png",
		"Cosmic Jump/Assets/background/sprite10-sheet0.png",
		"Cosmic Jump/Assets/background/sprite11-sheet0.png",
		"Cosmic Jump/Assets/background/gotoyouwin-sheet0.png",
		"Cosmic Jump/Assets/background/coin-sheet0.png",
		"Cosmic Jump/lobo loco - meet you in tibet (id 1491).ogg",
		"Cosmic Jump/242857__plasterbrain__coin-get.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}